import { FC, PropsWithChildren } from 'react'
import styles from './MainLayaout.module.css'
import Head from 'next/head'
import { Navbar } from '../Navbar'


export const MainLayaout: FC <PropsWithChildren> = ({ children }) => {
	return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar/>

            <h1>Home</h1>
            <main className={styles.main}>
				{ children }
            </main>
        </>
    )
}
